-- Run from the repository root: nvim --clean --headless -l tests/run.lua
vim.opt.runtimepath:prepend(vim.fn.getcwd())
dofile('tests/unit.lua')
local api = vim.api
local focus = require('prose_focus')
local function flush()
  local done = false
  vim.schedule(function() done = true end)
  assert(vim.wait(1000, function() return done end), 'scheduled update timed out')
end

api.nvim_buf_set_lines(0, 0, -1, true, { 'First sentence. Another one.', '', 'Second paragraph.' })
vim.bo.filetype = 'text'
vim.bo.modified = false
vim.fn.setreg('/', 'unchanged-search')
vim.fn.setreg('a', 'unchanged-register')
api.nvim_buf_set_mark(0, 'a', 3, 0, {})
local before = api.nvim_buf_get_lines(0, 0, -1, true)
local tick = api.nvim_buf_get_changedtick(0)
local undo = vim.fn.undotree().seq_cur
local cursor = api.nvim_win_get_cursor(0)
focus.setup({ mode = 'sentence' })
flush()
assert(vim.deep_equal(cursor, api.nvim_win_get_cursor(0)))
assert(vim.deep_equal(before, api.nvim_buf_get_lines(0, 0, -1, true)))
assert(tick == api.nvim_buf_get_changedtick(0))
assert(undo == vim.fn.undotree().seq_cur)
assert(not vim.bo.modified)
assert(vim.fn.getreg('/') == 'unchanged-search')
assert(vim.fn.getreg('a') == 'unchanged-register')
assert(vim.deep_equal(api.nvim_buf_get_mark(0, 'a'), { 3, 0 }))
local ns = api.nvim_create_namespace('prose_focus')
assert(#api.nvim_buf_get_extmarks(0, ns, 0, -1, {}) == 0, 'no persistent extmarks')
vim.cmd('vsplit')
api.nvim_win_set_cursor(0, { 3, 0 })
focus.refresh()
flush()
vim.cmd('ProseFocus paragraph')
flush()
focus.disable()
flush()
focus.enable()
flush()
focus.setup({ enabled = false, highlight = 'Comment' })
flush()
assert(not pcall(focus.setup, { typo = true }))
assert(not pcall(focus.setup, { dim = -1 }))
assert(not pcall(focus.set_mode, 'word'))
vim.cmd('only')
print('prose_focus: Neovim lifecycle smoke tests passed')
